server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    property-naming-strategy: SNAKE_CASE
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: gemma2-9b-it
          temperature: 0.3

ai:
  sections:
    # 사업위험
    risk_industry:
      prompt: "classpath:prompts/risk_industry.st"
      sources: [news, db]
      label: "사업위험"

    # 회사위험
    risk_company:
      prompt: "classpath:prompts/risk_company.st"
      sources: [web, db]
      label: "회사위험"

    # 기타위험
    risk_etc:
      prompt: "classpath:prompts/risk_etc.st"
      sources: [web, db]
      label: "기타 투자위험"

  # 컨트롤러/오케스트레이터가 돌릴 기본 처리 순서(선택)
  default-order: [risk_industry, risk_company, risk_etc]

# Opensearch - 보안X(HTTP, 기본 인증 없음)
opensearch:
  uris: ${OPENSEARCH_URIS}
  connection-timeout: 5s     # connect timeout
  socket-timeout: 60s        # read timeout
  max-conn-total: 100
  max-conn-per-route: 100
  sniff-enabled: false       # Managed/로컬 모두 기본 false 권장
