server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    property-naming-strategy: SNAKE_CASE
  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: 1
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
        options:
          model: "qwen2.5:3b"
          temperature: 0.3
      init:
        pull-model-strategy: never

# prompt 경로 및 Section 매핑
ai:
  defaults:
    maxItems: 5
    webRagItems: [ ]      # 더미
    dartRagItems: [ ]     # 더미
  prompts:
    draft_default: "classpath:prompts/draft_default.st"
    validator_default: "classpath:prompts/validator_default.st"
    validator_risk: "classpath:prompts/validator_risk.st"
    validator_user: "classpath:prompts/validator_user.st"
    adjust_default: "classpath:prompts/adjust_default.st"
    adjust_user: "classpath:prompts/adjust_user.st"

  sections:
    # 사업위험
    risk_industry:
      prompt: "classpath:prompts/risk_industry.st"
      sources: [news, db]
      label: "사업위험"
      filter: "industry"

    # 회사위험
    risk_company:
      prompt: "classpath:prompts/risk_company.st"
      sources: [web, db]
      label: "회사위험"
      filter: "financial"

    # 기타위험
    risk_etc:
      prompt: "classpath:prompts/risk_etc.st"
      sources: [web, db]
      label: "기타 투자위험"
      filter: "latest"

  # main 랭그래프 실행 section 지정 리스트
#  default-order: [risk_industry, risk_company, risk_etc]
  default-order: [risk_industry]

# Opensearch - 보안X(HTTP, 기본 인증 없음)
opensearch:
  uris: ${OPENSEARCH_URIS}
  connection-timeout: 5s     # connect timeout
  socket-timeout: 60s        # read timeout
  max-conn-total: 100
  max-conn-per-route: 100
  sniff-enabled: false       # Managed/로컬 모두 기본 false 권장
