server:
  port: 8080



spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    property-naming-strategy: SNAKE_CASE
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: gemma2-9b-it
          temperature: 0.3
    # --- MCP Client: STDIO로 DuckDuckGo MCP를 자식 프로세스로 실행 ---
    mcp:
      client:
        enabled: true
        type: SYNC     # SYNC or ASYNC
        stdio:
          connections:
            duck: # 연결 이름
              command: "C:/Users/jyjj0/.mcpvenv/Scripts/duckduckgo-mcp-server.exe"  # ddg mcp path
              args: [ ]
              # env:
              #   HTTP_PROXY: ${HTTP_PROXY:}
              #   HTTPS_PROXY: ${HTTPS_PROXY:}

ai:
  sections:
    # 사업위험
    risk_industry:
      prompt: "classpath:prompts/risk_industry.st"
      sources: [web, db]

    # 회사위험
    risk_company:
      prompt: "classpath:prompts/risk_company.st"
      sources: [web, db]

    # 기타위험
    risk_etc:
      prompt: "classpath:prompts/risk_etc.st"
      sources: [web, db]

  # 컨트롤러/오케스트레이터가 돌릴 기본 처리 순서(선택)
  default-order: [risk_industry, risk_company, risk_etc]

# 로컬/개인 운영(HTTP, 기본 인증 없음)
opensearch:
  uris: ${OPENSEARCH_URIS}
  connection-timeout: 5s     # connect timeout
  socket-timeout: 60s        # read timeout
  max-conn-total: 100
  max-conn-per-route: 100
  sniff-enabled: false       # Managed/로컬 모두 기본 false 권장

# AWS OpenSearch Service(도메인 엔드포인트, SigV4 서명)
#opensearch:
#  uris:
#    - https://search-your-domain-id.ap-northeast-2.es.amazonaws.com
#  connection-timeout: 5s
#  socket-timeout: 60s
#  max-conn-total: 200
#  max-conn-per-route: 100
#  sniff-enabled: false          # ★ AWS에서는 반드시 false
#  aws:
#    sigv4-enabled: true
#    region: ap-northeast-2
#    service: es                 # OpenSearch Service=es, Serverless는 aoss
#    credentials:
#      access-key: ${AWS_ACCESS_KEY_ID:}
#      secret-key: ${AWS_SECRET_ACCESS_KEY:}
#      session-token: ${AWS_SESSION_TOKEN:}   # (옵션) 임시자격증명 사용 시

# mapping 띄어쓰기에 따라 달라지는 검색결과 때문에 만든 부분
# 순서대로 사업 위험- 회사위험- 기타 위험요소
risk:
  business-keyword-map:
    시장 전망: "시장 전망,시장전망"
    산업 동향: "산업 동향,산업동향"
    경쟁 심화: "경쟁 심화,경쟁심화,경쟁 격화,경쟁격화"
    시장 점유율: "시장 점유율,시장점유율"
    판매 단가 하락: "판매 단가 하락,판매단가 하락,판매단가하락"

    신규 규제: "신규 규제,신규규제"
    정부 정책 변화: "정부 정책 변화,정부정책 변화,정부정책변화"
    법적 진입장벽: "법적 진입 장벽,법적 진입장벽,법적진입장벽"

    기술 변화: "기술 변화,기술변화"
    신기술 개발: "신기술 개발,신기술개발"
    제품 수명주기: "제품 수명 주기,제품수명 주기,제품수명주기"
    연구개발 투자: "연구 개발 투자,연구개발 투자,연구개발투자"
    연구개발 실패: "연구 개발 실패,연구개발 실패,연구개발실패"

    매출 편중: "매출 편중,매출편중"
    매출처 집중: "매출처 집중,매출 처 집중"
    주요 고객 의존: "주요 고객 의존,주요고객 의존,주요고객의존"
    거래처 악화: "거래처 악화,거래처악화"

    원자재 가격 상승: "원자재 가격 상승,원자재가격 상승,원자재가격상승"
    공급망 리스크: "공급 망 리스크,공급망 리스크,공급망리스크"
    핵심 부품 부족: "핵심 부품 부족,핵심부품 부족,핵심부품부족"
    외주 차질: "외주 차질,외주차질"

    연구개발 중단: "연구 개발 중단,연구개발 중단,연구개발중단"
    연구개발 보조금 중단: "연구 개발 보조금 중단,연구개발 보조금 중단,연구개발보조금 중단,연구개발보조금중단"
    핵심 인력 유출: "핵심 인력 유출,핵심인력 유출,핵심인력유출"
    연구개발 지연: "연구 개발 지연,연구개발 지연,연구개발지연"

    임상시험 실패: "임상 시험 실패,임상시험 실패,임상시험실패"
    신약 개발: "신약 개발,신약개발"
    라이선스 아웃: "라이선스 아웃,라이선스아웃"
    메타버스 플랫폼: "메타버스 플랫폼,메타버스플랫폼"
    신규 사업 실패: "신규 사업 실패,신규사업 실패,신규사업실패"
    유전 개발: "유전 개발,유전개발"
    자원 개발 리스크: "자원 개발 리스크,자원개발 리스크,자원개발리스크"
    기술특례 상장: "기술 특례 상장,기술특례 상장,기술특례상장"
    IP 분쟁: "IP 분쟁,IP분쟁"
  company-keyword-map:
    재무 상태 악화: "재무 상태 악화,재무상태 악화,재무상태악화"
    유동성 위기: "유동성 위기,유동성위기"
    차입금 증가: "차입금 증가,차입금증가"
    채무 상환능력: "채무 상환 능력,채무상환 능력,채무상환능력"
    이자보상비율 하락: "이자 보상 비율 하락,이자보상 비율 하락,이자보상비율 하락"
    영업 현금흐름 적자: "영업 현금흐름 적자,영업현금흐름 적자,영업현금흐름적자"
    현금흐름 악화: "현금 흐름 악화,현금흐름 악화,현금흐름악화"
    매출 감소: "매출 감소,매출감소"
    수익성 악화: "수익성 악화,수익성악화"
    영업 적자: "영업 적자,영업적자"
    매출채권 회수 불능: "매출 채권 회수 불능,매출채권 회수 불능,매출채권 회수불능"
    재고자산 증가: "재고 자산 증가,재고자산 증가,재고자산증가"
    재고자산 감액 손실: "재고 자산 감액 손실,재고자산 감액 손실,재고자산감액손실"
    영업권 손상: "영업 권 손상,영업권 손상,영업권손상"
    유형자산 진부화: "유형 자산 진부화,유형자산 진부화,유형자산진부화"
    연구개발비 증가: "연구 개발비 증가,연구개발비 증가,연구개발비증가"
    개발 실패 손실: "개발 실패 손실,개발실패 손실,개발실패손실"
    영업실적 악화: "영업 실적 악화,영업실적 악화,영업실적악화"
    지속 가능성 위기: "지속 가능성 위기,지속가능성 위기,지속가능성위기"
    기업가치 하락: "기업 가치 하락,기업가치 하락,기업가치하락"

  other-keyword-map:
    전환사채 발행: "전환 사채 발행,전환사채 발행,전환사채발행"
    신주인수권부사채: "신주 인수권부 사채,신주인수권부 사채,신주인수권부사채"
    주가 희석: "주가 희석,주가희석"
    보호예수 해제: "보호 예수 해제,보호예수 해제,보호예수해제"
    대주주 지분 매각: "대주주 지분 매각,대주주지분 매각,대주주지분매각"
    외국투자자 대량 매도: "외국 투자자 대량 매도,외국투자자 대량 매도,외국투자자대량매도"
    유통주식 부족: "유통 주식 부족,유통주식 부족,유통주식부족"
    실권주 인수: "실 권주 인수,실권주 인수,실권주인수"
    실권주 매각: "실 권주 매각,실권주 매각,실권주매각"
    주가 급등: "주가 급 등,주가 급등,주가급등"
    주가 급락: "주가 급 락,주가 급락,주가급락"
    상장폐지 위험: "상장 폐지 위험,상장폐지 위험,상장폐지위험"
    관리종목 지정: "관리 종목 지정,관리종목 지정,관리종목지정"
    신주 발행 분쟁: "신주 발 행 분쟁,신주 발행 분쟁,신주발행 분쟁,신주발행분쟁"
    유상증자 분쟁: "유상 증자 분쟁,유상증자 분쟁,유상증자분쟁"
    신주발행 무효 소송: "신주 발행 무효 소송,신주발행 무효 소송,신주발행 무효소송,신주발행무효소송"


