server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: gemma2-9b-it
          temperature: 0.3

# 로컬/개인 운영(HTTP, 기본 인증 없음)
opensearch:
  uris: ${OPENSEARCH_URIS}
  connection-timeout: 5s     # connect timeout
  socket-timeout: 60s        # read timeout
  max-conn-total: 100
  max-conn-per-route: 100
  sniff-enabled: false       # Managed/로컬 모두 기본 false 권장

# AWS OpenSearch Service(도메인 엔드포인트, SigV4 서명)
#opensearch:
#  uris:
#    - https://search-your-domain-id.ap-northeast-2.es.amazonaws.com
#  connection-timeout: 5s
#  socket-timeout: 60s
#  max-conn-total: 200
#  max-conn-per-route: 100
#  sniff-enabled: false          # ★ AWS에서는 반드시 false
#  aws:
#    sigv4-enabled: true
#    region: ap-northeast-2
#    service: es                 # OpenSearch Service=es, Serverless는 aoss
#    credentials:
#      access-key: ${AWS_ACCESS_KEY_ID:}
#      secret-key: ${AWS_SECRET_ACCESS_KEY:}
#      session-token: ${AWS_SESSION_TOKEN:}   # (옵션) 임시자격증명 사용 시